apiVersion: serving.knative.dev/v1beta1
kind: DomainMapping
metadata:
  name: labs.jininfra.cloud
  namespace: study
spec:
  ref:
    apiVersion: serving.knative.dev/v1
    kind: Service
    name: portal
