apiVersion: v1
kind: ConfigMap
metadata:
  name: config-gateway
  namespace: knative-serving
data:
  external-gateways: |
    - class: istio
      gateway: knative-serving/knative-ingress-gateway
      service: knative-serving/knative-ingress-gateway-istio
      supported-features:
      - HTTPRouteRequestTimeout
  local-gateways: |
    - class: istio
      gateway: knative-serving/knative-local-gateway
      service: knative-serving/knative-local-gateway-istio
      supported-features:
      - HTTPRouteRequestTimeout
