apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: knative-ingress-gateway
  namespace: knative-serving
spec:
  gatewayClassName: istio
  listeners:
    - name: http
      hostname: "*.labs.jininfra.cloud"
      port: 80
      protocol: HTTP
      allowedRoutes:
        namespaces:
          from: All
    - name: http-study
      hostname: "*.study.labs.jininfra.cloud"
      port: 80
      protocol: HTTP
      allowedRoutes:
        namespaces:
          from: All
    - name: http-root
      hostname: "labs.jininfra.cloud"
      port: 80
      protocol: HTTP
      allowedRoutes:
        namespaces:
          from: All
    - name: https-root
      hostname: "labs.jininfra.cloud"
      port: 443
      protocol: HTTPS
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            name: portal-labs-jininfra-cloud-tls
      allowedRoutes:
        namespaces:
          from: All
    - name: https-portal-study
      hostname: "portal.study.labs.jininfra.cloud"
      port: 443
      protocol: HTTPS
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            name: portal-labs-jininfra-cloud-tls
      allowedRoutes:
        namespaces:
          from: All